In [1]:
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import math
from matplotlib.animation import FuncAnimation
from IPython.display import HTML

In [46]:
def gradient(w_in, c_in):
    
    product = np.multiply(np.dot(c_in, w_in), 2)
    return product

In [ ]:
def grad(w_in):
    return b + ((c + c.transpose) @ w_in )

In [109]:
a = 0

b = np.array([[0], 
              [0]])
c = np.array([[0.5, 0],
              [0, 9.75]])

def g(w_in):
    return a + (b.transpose() @ w_in) + (w_in.transpose() @ c) @ w_in

In [110]:
g(w_x)

array([[59.75]])

In [111]:
3**2

9

In [105]:
w_x = np.array([[10], 
                [1]]) 
ax = 0

bx = np.array([[4], 
              [5]])
cx = np.array([[0.5, 0],
              [0, 9.75]])

In [102]:
w_x + bx

array([[14],
       [ 6]])

In [98]:
w_x.transpose() @ cx

array([[ 5.  , 19.75]])

In [118]:
def gradientDescentWithMomentum(beta = 0, num_iter=25, w_0 = None, a=0, b=np.zeros((2,1)), c = np.zeros((2,2)),lr = 0.1):

    def grad(w_in):
        return b + ((c + c.transpose()) @ w_in )
    
    w_history = [] #List of w's in each iteration, used to plot
   
    w = w_0
    
    w_history.append(w)
    
    for i in range(num_iter):
        #Update momentum and w
        #Add new w to list
        
        #this one is for when beta is 0
        #grad_eval = grad(w, c)
        grad_eval = grad(w)
        
        #update w
        w = np.add(w, -(np.multiply(lr,grad_eval)))
        
        #record weight
        w_history.append(w)
        
        pass
    ### YOUR CODE ENDS HERE    
        
    return w, w_history
    
    ### YOUR CODE STARTS HERE

In [120]:
w_x = np.array([[10], 
                [1]]) 
ax = 0

bx = np.array([[0], 
              [0]])
cx = np.array([[0.5, 0],
              [0, 9.75]])

gradientDescentWithMomentum(0,25,w_x,ax, bx, cx)

(array([[ 0.71789799],
        [-0.27738957]]),
 [array([[10],
         [ 1]]),
  array([[ 9.  ],
         [-0.95]]),
  array([[8.1   ],
         [0.9025]]),
  array([[ 7.29    ],
         [-0.857375]]),
  array([[6.561     ],
         [0.81450625]]),
  array([[ 5.9049    ],
         [-0.77378094]]),
  array([[5.31441   ],
         [0.73509189]]),
  array([[ 4.782969 ],
         [-0.6983373]]),
  array([[4.3046721 ],
         [0.66342043]]),
  array([[ 3.87420489],
         [-0.63024941]]),
  array([[3.4867844 ],
         [0.59873694]]),
  array([[ 3.13810596],
         [-0.56880009]]),
  array([[2.82429536],
         [0.54036009]]),
  array([[ 2.54186583],
         [-0.51334208]]),
  array([[2.28767925],
         [0.48767498]]),
  array([[ 2.05891132],
         [-0.46329123]]),
  array([[1.85302019],
         [0.44012667]]),
  array([[ 1.66771817],
         [-0.41812034]]),
  array([[1.50094635],
         [0.39721432]]),
  array([[ 1.35085172],
         [-0.3773536 ]]),
  array([[1.21

In [130]:
w_0 = np.array([[10], 
                [1]]) 
### YOUR CODE STARTS FROM HERE
#Coefficients of g(w)
a = 0

b = np.array([[0], 
              [0]])
c = np.array([[0.5, 2],
              [1, 9.75]])



In [133]:
def NewtonsMethodwithSubSampling(num_iter=25, w_0 = None, a=0, b=np.zeros((2,1)), c = np.zeros((2,2))):
    '''
        num_iter = number of iterations in gradient descent
        w_0: initial w
        a, b, c: coefficients of the function
    '''
    #Initialize variables
    w_history = [] #List of w's in each iteration, used to plot
    epsilon = 1e-6 # Add it to denominator to avoid division by zero
    
    if w_0 is not None: #Initial w
        w = w_0
    else:
        w = np.random.rand(2,1) #If no w_0 is given, initialize it randomly between [0, 1]
    
    ### YOUR CODE STARTS FROM HERE
    
    
   
    
    
    # You may want to code the g(w) and gradient functions here or compute the gradients at each step, it is up to you.
    
    def gradient2(w_in):
        return b + ((c + c.transpose()) @ w_in )
    
    def newtons2(w_in): 
        temp = np.array([[0.5/(c[0][0]+epsilon), 0],
                         [0, 0.5/(c[1][1]+epsilon)]])
        
        w_temp = gradient2(w_in)
        
        return temp @ w_temp 
    
    def gradient(w_in, c_in, b_in):
        temp = np.zeros((2,1))
        temp[0] = b_in[0] + (2*(w_in[0]*c_in[0][0])) + ((c_in[0][1]*c_in[1][0])*w_in[1])
        temp[1] = b_in[1] + (2*(w_in[1]*c_in[1][1])) + ((c_in[0][1]*c_in[1][0])*w_in[0])
        return temp
    
    def second_deriv(c_in,eps):
        temp = np.zeros((2,1))
        temp[0] = (2*c_in[0][0])+eps
        temp[1] = (2*c_in[1][1])+eps
        return temp
    
    def newtons(numerator,denominator):
        temp = np.zeros((2,1))
        temp[0] = numerator[0]/denominator[0]
        temp[1] = numerator[1]/denominator[1]
        return temp
        
      
        
    #Calculate gradients of initial w_0 (Don't forget to add w_0 to w_history list!)
    
    
    
    #Newton's Method steps
    
    w_history.append(w)   
    
    for i in range(num_iter):
        #Update w, add w to w_history
        
        #grad_eval = gradient(w,c,b)
        
        #stopping condition
        #if (grad_eval[0]*grad_eval[0])+(grad_eval[1]*grad_eval[1]) <= 0.001:
            #break
        
        #update w
        #w = np.add(w, -(newtons(gradient(w,c,b),second_deriv(c,epsilon))))
        w = w - newtons2(w)
        #record weight
        w_history.append(w)
        
        pass
 
    
    
        
    ### YOUR CODE ENDS HERE
    return w, w_history

In [460]:
arr1, arr2 = NewtonsMethodwithSubSampling(25, w_0, a, b, c)

In [490]:
arrays = np.array(arr2)
arrays

array([[[ 1.00000000e+01],
        [ 1.00000000e+00]],

       [[-2.99997400e+00],
        [-1.53846128e+00]],

       [[ 4.61536860e+00],
        [ 4.61534256e-01]],

       [[-1.38459077e+00],
        [-7.10056588e-01]],

       [[ 2.13016273e+00],
        [ 2.13013870e-01]],

       [[-6.39036071e-01],
        [-3.27717288e-01]],

       [[ 9.83148621e-01],
        [ 9.83131980e-02]],

       [[-2.94937038e-01],
        [-1.51253608e-01]],

       [[ 4.53759328e-01],
        [ 4.53749087e-02]],

       [[-1.36123546e-01],
        [-6.98091155e-02]],

       [[ 2.09426655e-01],
        [ 2.09420748e-02]],

       [[-6.28256798e-02],
        [-3.22194800e-02]],

       [[ 9.66581210e-02],
        [ 9.66548490e-03]],

       [[-2.89962034e-02],
        [-1.48704776e-02]],

       [[ 4.46112857e-02],
        [ 4.46095239e-03]],

       [[-1.33827412e-02],
        [-6.86327356e-03]],

       [[ 2.05897527e-02],
        [ 2.05888234e-03]],

       [[-6.17659349e-03],
        [-3.16765373e

In [481]:
x

-2.999974000051999

In [494]:
xs = []
ys = []
 
for i in range(25):
    x = arrays[i][0]
    y = arrays[i][1]
    xs.append(x)
    ys.append(y)
        
        #ax.plot(xs, ys)
plt.plot(xs,ys, 'ro-')

In [117]:
gradientDescentWithMomentum(0,25,w_x,ax, bx, cx)

TypeError: unsupported operand type(s) for +: 'float' and 'builtin_function_or_method'

In [64]:
beta_param = np.array([0, 0.2, 0.7])
num_of_runs = 3
for i in range(num_of_runs):
    print(beta_param[i])

0.0
0.2
0.7


In [391]:
def load_data(csvname):
    data = np.asarray(pd.read_csv(csvname,header = None))
    x = data[:,0]
    x.shape = (np.size(x),1)
    temp = np.ones((np.size(x),1))
    X = np.concatenate((temp,x),1)
    y = data[:,1]
    y = y/y.max()
    y.shape = (np.size(y),1)
    return X,y

In [392]:
X,y = load_data('bacteria_data.csv') 

In [393]:
def compute_cost(w):
    temp = 1/(1 + my_exp(-np.dot(X,w))) - y
    temp = np.dot(temp.T,temp)
    return temp

# avoid overflow when using exp - just cutoff after arguments get too large/small
def my_exp(u):
    s = np.argwhere(u > 100)
    t = np.argwhere(u < -100)
    u[s] = 0
    u[t] = 0
    u = np.exp(u)
    u[t] = 1
    return u

In [394]:
X

array([[ 1.,  0.],
       [ 1.,  3.],
       [ 1.,  6.],
       [ 1.,  9.],
       [ 1., 12.],
       [ 1., 15.],
       [ 1., 18.],
       [ 1., 21.],
       [ 1., 24.]])

In [397]:
y[5][0]

0.7589

In [396]:
y

array([[0.06274 ],
       [0.078356],
       [0.13781 ],
       [0.28356 ],
       [0.56712 ],
       [0.7589  ],
       [0.90959 ],
       [1.      ],
       [0.98904 ]])

In [457]:
w = np.array([0,2])
w1 = np.array([[0],
               [2]])

w0.shape = (2,1)

In [458]:
w_temp = w1
w_temp[0] = 0

In [459]:
w_temp

array([[0],
       [2]])

In [433]:
w1.shape

(2, 1)

In [398]:
X[6] @ w

36.0

In [399]:
compute_cost(w)

array([[1.27546623, 1.13261816, 1.13191   , 1.13190824, 1.13190823,
        1.13190823, 1.13190823, 1.13190823, 1.13190823],
       [1.13261816, 3.21757151, 3.22790761, 3.2279333 , 3.22793336,
        3.22793336, 3.22793336, 3.22793336, 3.22793336],
       [1.13191   , 3.22790761, 3.23829847, 3.23832429, 3.23832435,
        3.23832435, 3.23832435, 3.23832435, 3.23832435],
       [1.13190824, 3.2279333 , 3.23832429, 3.23835011, 3.23835017,
        3.23835017, 3.23835017, 3.23835017, 3.23835017],
       [1.13190823, 3.22793336, 3.23832435, 3.23835017, 3.23835023,
        3.23835023, 3.23835023, 3.23835023, 3.23835023],
       [1.13190823, 3.22793336, 3.23832435, 3.23835017, 3.23835023,
        3.23835023, 3.23835023, 3.23835023, 3.23835023],
       [1.13190823, 3.22793336, 3.23832435, 3.23835017, 3.23835023,
        3.23835023, 3.23835023, 3.23835023, 3.23835023],
       [1.13190823, 3.22793336, 3.23832435, 3.23835017, 3.23835023,
        3.23835023, 3.23835023, 3.23835023, 3.23835023],


In [407]:
r=np.zeros((1,len(X)))

In [410]:
r[0][6]

0.0

In [445]:
def sigmoid(x):
    return 1 / (1 + math.exp(-x))

r=np.zeros((len(X),1))
for i in range(len(X)):
    param = X[i] @ w
    sigm = sigmoid(param)
    arg = 2 * (sigm-y[5][0])* sigm * (1 - sigm)
    r[i] = arg
    
    
 
    
    


In [446]:
X

array([[ 1.,  0.],
       [ 1.,  3.],
       [ 1.,  6.],
       [ 1.,  9.],
       [ 1., 12.],
       [ 1., 15.],
       [ 1., 18.],
       [ 1., 21.],
       [ 1., 24.]])

In [447]:
r

array([[-1.29450000e-01],
       [ 1.17715328e-03],
       [ 2.96262729e-06],
       [ 7.34389554e-09],
       [ 1.82037046e-11],
       [ 4.50764315e-14],
       [ 1.07069908e-16],
       [ 0.00000000e+00],
       [ 0.00000000e+00]])

In [448]:
result = X.transpose() @ r

In [449]:
result

array([[-0.12826988],
       [ 0.0035493 ]])

In [450]:
result.shape

(2, 1)

In [451]:
result[1]

array([0.0035493])

In [421]:
result.transpose()

array([[-0.12826988,  0.0035493 ]])

In [321]:
X.transpose() @ r

array([ -4.70249632, -38.53433546])

In [325]:
w

array([0.04702496, 2.38534335])

In [440]:
alpha = 10**(-2)        
        
grad = X.transpose() @ r
        
        # take gradient step
#w = w - alpha*grad

In [444]:
grad

array([[-0.12826988],
       [ 0.0035493 ]])

In [443]:
grad[1]


array([0.0035493])